import { chromium } from 'playwright';
const OUT = '.scratch/057_order-entry-zero-qty';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const pg = await b.newPage({ viewport: { width: 1300, height: 1200 }, deviceScaleFactor: 2 });
pg.on('console', m => { if (m.type() === 'error') console.log('PAGE ERR:', m.text()); });
pg.on('pageerror', e => console.log('PAGE THROW:', e.message));
await pg.goto('http://localhost:5199/.scratch/057_order-entry-zero-qty/preview.html', { waitUntil: 'networkidle' });
await pg.waitForTimeout(700);
await pg.screenshot({ path: `${OUT}/before-after.png`, fullPage: true });
console.log('shot taken');
await b.close();
