import { chromium } from "playwright";
const OUT = ".scratch/080_wedi-curb-names/shots";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const pg = await b.newPage({ viewport: { width: 1680, height: 980 }, deviceScaleFactor: 2 });
await pg.goto("http://127.0.0.1:5199/wedi-preview.html", { waitUntil: "load" });
await pg.waitForTimeout(1200);
await pg.locator(".modetab", { hasText: "Browse" }).click();
await pg.waitForTimeout(500);
await pg.locator(".browsebar input").fill("shower base");
await pg.waitForTimeout(500);
await pg.locator(".main").screenshot({ path: `${OUT}/8-browse-bases.png` });
console.log("first rows:", (await pg.locator(".brow .bn .n").allTextContents()).slice(0, 4).join(" | "));
await pg.locator(".browsebar input").fill("niche");
await pg.waitForTimeout(500);
console.log("niche rows:", (await pg.locator(".brow .bn .n").allTextContents()).slice(0, 3).join(" | "));
await pg.locator(".browsebar input").fill("cover");
await pg.waitForTimeout(500);
await pg.locator(".main").screenshot({ path: `${OUT}/9-browse-covers.png` });
console.log("cover rows:", (await pg.locator(".brow .bn .n").allTextContents()).slice(0, 3).join(" | "));
await pg.close(); await b.close();
